[package]
name = "echor"
version = "0.1.0"
edition = "2021"
description = "Clone of echo written in Rust!"

[dependencies]
assert_cmd = "2.0.16"
clap = { version = "4.5.17", features = ["derive"] }
predicates = "3.1.2"
